version: "3"

services:
  app:
   build: ./nginx
    image: magento-nginx:1.18-8
    ports:
      - "80:8000"
      - "443:8443"
    volumes: &appvolumes
      - ./src:/var/www/html:cached
      - ./media/pub:/var/www/html/media/pub:cached
      - ~/.composer:/var/www/.composer:cached
      - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - sockdata:/sock
      - ssldata:/etc/nginx/certs
    extra_hosts: &appextrahosts
       - "unfiltered.co.il:172.17.0.1"
       - "host.docker.internal:172.17.0.1"

  phpfpm:
   build: ./php
    image: magento-php:7.4-fpm
    volumes: *appvolumes
    env_file: env/phpfpm.env
    #extra_hosts: *appextrahosts

  db:
    image: mariadb:10.4
    command:
      --max_allowed_packet=64M
      --optimizer_use_condition_selectivity=1
      --optimizer_switch="rowid_filter=off"
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  elasticsearch:
   build: ./elasticsearch
    image: magento-elasticsearch:7.16-0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"

  rabbitmq:
   build: ./rabbitmq
    image: magento-rabbitmq:3.9-0
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    env_file: env/rabbitmq.env


volumes:
  appdata:
  dbdata:
  rabbitmqdata:
  sockdata:
  ssldata:
